@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/chat/message/user/<receiverId>
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "63f4e1376bcb69e85c7a7c43",
  "receiverId": "63f49dbcb2105f59c6fb20c1",
  "receiverUsername": "Manny",
  "receiverAvatarColor": "green",
  "receiverProfilePicture": "https://res.cloudinary.com/dprk3hqy8/image/upload/v1676975549/63f49dbcb2105f59c6fb20c1",
  "body": "How are you? kyrwa",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "63f49dc7b2105f59c6fb20c8",
  "userTwo": "63f49dbcb2105f59c6fb20c1"
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "63f49dc7b2105f59c6fb20c8",
  "userTwo": "63f49dbcb2105f59c6fb20c1"
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "",
  "receiverId": ""
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

# For this endpoint, the type is either add or remove
{
  "conversationId": "",
  "messageId": "",
  "reaction": "",
  "type": ""
}

###
DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/63f4e1376bcb69e85c7a7c42/63f4e1376bcb69e85c7a7c43/63f49dc7b2105f59c6fb20c7/deleteForMe
# For this endpoint, the type is either deleteForMe or deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true
