@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "63ac5ed7ebcbb3d60f82b5c3",
  "postId": "63c41ebf9bfb09f54dbc050a",
  "type": "happy",
  "previousReaction": "",
  "postReactions": {"like": 0,"love": 0,"happy": 0,"sad": 1,"wow": 0,"angry": 0},
    "profilePicture": "https://res.cloudinary.com/dprk3hqy8/image/upload/v1672240856/63ac5ed7ebcbb3d60f82b5c3"
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/62ea82366d7191261d4ff0de/sad/{"like": 0,"love": 0,"happy": 0,"sad": 0,"wow": 0,"angry": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/62ea82366d7191261d4ff0de
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/username/Manny/62ea82366d7191261d4ff0de
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/Danny
Content-Type: application/json
Accept: application/json
withCredentials: true
